# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
  displayName: 'Run a one-line script'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      set -x
      /c/hostedtoolcache/windows/go/1.14.13/x64/bin/go version
      /c/hostedtoolcache/windows/go/1.15.6/x64/bin/go version
      go version
      echo "GOROOT_1_15_X64: $GOROOT_1_15_X64"
      export "PATH=/c/hostedtoolcache/windows/go/1.15.6/x64/bin:$PATH"
      which go
      go version
